// lib/scoring-complete.ts
// Complete 118-point evaluation framework for UAE Website Channel Assessment
// All 11 pillars, exact order, with auto/manual flags and conditional logic

import type { CriterionDefinition, CriterionResult, Grade, PillarScore } from '@/lib/types';

// ════════════════════════════════════════════════════════════════════
// COMPLETE CRITERIA REGISTRY (118 POINTS)
// ════════════════════════════════════════════════════════════════════

export const CRITERIA: CriterionDefinition[] = [
  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 1: DISCOVERY & ACCESS (3 questions, 5 max points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q1a',
    nameEN: 'Please select entity category',
    nameAR: 'يرجى تحديد فئة الجهة',
    pillar: 'Discovery & Access',
    pillarAR: 'الاكتشاف والوصول',
    subPillar: 'Entity Classification',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    recommendation: 'Select the appropriate entity category (Tamm Website, Non-Tamm Entity, or Entity On Tamm)',
  },
  {
    qid: 'Q1',
    nameEN: 'Website appears on the first page of major search engines (e.g., Google) using entity full name',
    nameAR: 'التمكن من العثور على عنوان الموقع الإلكتروني الخاص بالجهة في الصفحة الأولى لمحركات البحث الكبرى (مثل جوجل) بإستخدام إسم الجهة الكامل',
    pillar: 'Discovery & Access',
    pillarAR: 'الاكتشاف والوصول',
    subPillar: 'Accessibility > Search Presence',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Submit website to Google Search Console and ensure proper SEO optimization with entity name in meta tags',
  },
  {
    qid: 'Q1b',
    nameEN: 'Website appears on the first page of major search engines (e.g., Google) using entity acronym',
    nameAR: 'التمكن من العثور على عنوان الموقع الإلكتروني الخاص بالجهة في الصفحة الأولى لمحركات البحث الكبرى (مثل جوجل) بإستخدام إسم الجهة المختصر',
    pillar: 'Discovery & Access',
    pillarAR: 'الاكتشاف والوصول',
    subPillar: 'Accessibility > Search Presence',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Optimize entity acronym in page content and metadata for search visibility',
  },
  {
    qid: 'Q3',
    nameEN: "Entity's website mentioned on Google Maps was correct. In case of No, please clarify and mention what is mentioned on Google Maps.",
    nameAR: 'الموقع الإلكتروني للجهة والمذكور على خرائط جوجل صحيح. في حال كانت الإجابة "لا"، يرجى التوضيح وذكر ما هو مذكور على خرائط Google.',
    pillar: 'Discovery & Access',
    pillarAR: 'الاكتشاف والوصول',
    subPillar: 'Accessibility > Contact Information',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Verify and update Google Maps business profile to ensure correct website URL is listed',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 2: ACCESSIBILITY & INCLUSION (9 questions, 11 max points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q4',
    nameEN: 'Website offers content in multiple languages',
    nameAR: 'يتوفر محتوى الموقع الإلكتروني بلغات متعددة',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Multilingual Support',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add language switcher for Arabic and English support with proper hreflang tags',
  },
  {
    qid: 'Q5',
    nameEN: 'Language switching option is straightforward',
    nameAR: 'خيار تبديل اللغة واضح وسهل الاستخدام',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Multilingual Support',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q4',
    dependsOnValue: '2',
    recommendation: 'Place language switcher in header or prominent navigation area',
  },
  {
    qid: 'Q6',
    nameEN: 'Language switching option is available on all pages',
    nameAR: 'توفر خيار تبديل اللغة في جميع الصفحات',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Multilingual Support',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q4',
    dependsOnValue: '2',
    recommendation: 'Ensure language switcher is part of the global layout component on all pages',
  },
  {
    qid: 'Q7',
    nameEN: 'All images have descriptive alternative text. Note: check the availability of text that will be displayed if users hover over images.',
    nameAR: 'جميع الصور تحتوي على نص وصفي بديل. ملاحظة: تحقق من توفر النص الذي سيظهر إذا تم تمرير المؤشر فوق الصور.',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Compliance',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add meaningful alt text to all images; use title attributes for hover text',
  },
  {
    qid: 'Q7-sub',
    nameEN: 'Is the descriptive alternative text displayed in the same language as the selected website language and relevant to the page content?',
    nameAR: 'هل يتم عرض النص البديل الوصفي بنفس لغة الموقع المختارة ومرتبط بمحتوى الصفحة؟',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Compliance',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q7',
    recommendation: 'Ensure alt text language matches page language and is contextually relevant',
  },
  {
    qid: 'Q8',
    nameEN: 'Text resizing feature is available and functional',
    nameAR: 'توفر خاصية تغيير حجم النص وفعاليتها بشكل جيد',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Usability for All / POD',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add A+/A- buttons or accessibility toolbar with text resizing controls',
  },
  {
    qid: 'Q9',
    nameEN: 'Website content is compatible with screen readers and allows text to be read aloud. Note: Test by selecting text and using the built-in accessibility feature or browser screen reader support.',
    nameAR: 'محتوى الموقع متوافق مع قارئات الشاشة ويتيح قراءة النصوص بصوت مسموع.',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Usability for All / POD',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Use semantic HTML elements and ARIA labels; ensure all content is text-accessible',
  },
  {
    qid: 'Q10',
    nameEN: 'Adjusting the color contrast settings according to users preferences feature is available and functional',
    nameAR: 'توفر خاصية ضبط إعدادات تباين الألوان وفقًا لتفضيل المستخدم وتعمل بشكل جيد',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Usability for All / POD',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Implement high-contrast mode toggle or accessibility toolbar',
  },
  {
    qid: 'Q11',
    nameEN: 'Website provides a feature to convert text content into sign language videos or animations for users',
    nameAR: 'يوفر الموقع خاصية تحويل محتوى النص إلى مقاطع فيديو بلغة الإشارة للمتعاملين من أصحاب الهمم',
    pillar: 'Accessibility & Inclusion',
    pillarAR: 'إمكانية الوصول والشمولية',
    subPillar: 'Accessibility > Usability for All / POD',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Consider adding sign language video widget for inclusive accessibility',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 3: WEBSITE STRUCTURE & APPEARANCE (3 questions, 3 max points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q14',
    nameEN: 'Layout is consistent across all pages. Note: Check if the same layout is used when viewing multiple pages of the website.',
    nameAR: 'مظهر الموقع الإلكتروني متناسق عبر جميع الصفحات. ملاحظة: تحقق من توفر نفس المظهر والتخطيط عند عرض صفحات متعددة من الموقع.',
    pillar: 'Website Structure',
    pillarAR: 'هيكل الموقع والمظهر',
    subPillar: 'Appearance > User Interface',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Use consistent header, navigation, and footer across all pages using a shared layout template',
  },
  {
    qid: 'Q15',
    nameEN: 'Device agnostic: scalability of the website through handheld devices such as mobile phones, tablets, etc.',
    nameAR: 'الموقع الإلكتروني متوافق مع جميع الأجهزة المحمولة (الهواتف المحمولة والأجهزة اللوحية، إلخ)',
    pillar: 'Website Structure',
    pillarAR: 'هيكل الموقع والمظهر',
    subPillar: 'Appearance > User Interface',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add responsive viewport meta tag and CSS media queries for mobile devices',
  },
  {
    qid: 'Q15b',
    nameEN: 'Use of clear, relevant, and visually appealing images and videos',
    nameAR: 'استخدام صور ومقاطع فيديو واضحة، ذات صلة، وجذابة بصريًا',
    pillar: 'Website Structure',
    pillarAR: 'هيكل الموقع والمظهر',
    subPillar: 'Appearance > User Interface',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Include high-quality images and embedded videos in page content',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 4: NAVIGATION & EASE OF USE (12 questions, 17 max points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q12',
    nameEN: 'Social media links are available and functional',
    nameAR: 'توفر روابط وسائل التواصل الاجتماعي وفعاليتها بشكل جيد',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Accessibility > Social Media Integration',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add working social media links to Facebook, Twitter/X, LinkedIn, Instagram, YouTube in footer',
  },
  {
    qid: 'Q13',
    nameEN: 'Search bar is easily accessible on all pages',
    nameAR: 'سهولة الوصول إلى شريط البحث في جميع صفحات الموقع الإلكتروني',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > Search Functionality',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add a visible search bar in the header accessible on all pages',
  },
  {
    qid: 'Q16',
    nameEN: 'Contact details listed on the website: Phone number, Email address, Physical address / map',
    nameAR: 'يحتوي الموقع الإلكتروني على معلومات التواصل مع الجهة: رقم الهاتف، عنوان البريد الإلكتروني، العنوان / الخريطة',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > Contact Information',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Provide phone, email, and address/map in a dedicated contact section',
  },
  {
    qid: 'Q18',
    nameEN: 'Main menu categories are clearly labeled. Note: main tabs are labeled with clear names.',
    nameAR: 'وضوح عناصر وخيارات القائمة الرئيسية. ملاحظة: يتم تسمية الخيارات الرئيسية بأسماء واضحة.',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > Navigation',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Use descriptive menu labels avoiding generic terms like "Miscellaneous"',
  },
  {
    qid: 'Q19',
    nameEN: 'Content is free from jargon and easy to understand. Note: does not contain abbreviations or technical jargon.',
    nameAR: 'محتوى الموقع الإلكتروني سهل الفهم ويخلو من المصطلحات الفنية. ملاحظة: لا يحتوي على اختصارات أو مصطلحات تقنية.',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > Content Clarity',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Write content in plain language avoiding technical jargon and excessive abbreviations',
  },
  {
    qid: 'Q20',
    nameEN: 'Buttons and links are clearly labeled',
    nameAR: 'وضوح الروابط والأزرار',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > User Interface',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Use descriptive link text and clear button labels; avoid "click here"',
  },
  {
    qid: 'Q21',
    nameEN: 'Search results are relevant and accurate',
    nameAR: 'الحصول على نتائج بحث دقيقة وذات صلة',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > Search Functionality',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q13',
    dependsOnValue: 'yes',
    recommendation: 'Implement proper site search indexing with relevant result ranking',
  },
  {
    qid: 'Q22',
    nameEN: 'FAQ are easy to find and navigate',
    nameAR: 'سهولة العثور وتصفح صفحة الأسئلة الشائعة',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > Assistance Availability',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Create an accessible FAQ section with accordion or organized Q&A format',
  },
  {
    qid: 'Q30',
    nameEN: 'Navigation between pages and links is smooth and allows users to move easily using back and forward buttons.',
    nameAR: 'التنقل بين الصفحات والروابط سلس ويتيح للمستخدمين الانتقال بسهولة باستخدام أزرار الرجوع والتقدم.',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > Navigation',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Ensure smooth page transitions and proper browser back/forward functionality',
  },
  {
    qid: 'Q17',
    nameEN: 'Feedback forms or surveys about the website experience are available on the website.',
    nameAR: 'نماذج الملاحظات أو الاستبيانات الخاصة بتجربة الموقع متاحة على الموقع الإلكتروني.',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > User Feedback',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add feedback form or survey widget accessible from main navigation',
  },
  {
    qid: 'Q17.1',
    nameEN: 'Feedback forms or surveys are easy to find and complete.',
    nameAR: 'نماذج الملاحظات أو الاستبيانات يسهل العثور عليها واستكمالها.',
    pillar: 'Navigation',
    pillarAR: 'التنقل وسهولة الاستخدام',
    subPillar: 'Ease of Use > User Feedback',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q17',
    dependsOnValue: 'yes',
    recommendation: 'Place feedback form in header or top nav; keep form short and simple',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 5: REGISTRATION (3 questions, 0 max scored points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q23',
    nameEN: 'User registration is available on the website',
    nameAR: 'توفر خاصية تسجيل المستخدم',
    pillar: 'Registration',
    pillarAR: 'التسجيل',
    subPillar: 'Ease of Use > Registration',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add login/register functionality with secure authentication',
  },
  {
    qid: 'Q23a',
    nameEN: 'UAE Pass is available on the website',
    nameAR: 'تتوفر خاصية تسجيل الدخول باستخدام الهوية الرقمية',
    pillar: 'Registration',
    pillarAR: 'التسجيل',
    subPillar: 'Ease of Use > Registration',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q23',
    dependsOnValue: 'yes',
    recommendation: 'Integrate UAE Pass (Digital ID) login option',
  },
  {
    qid: 'Q24',
    nameEN: 'Registration process is straightforward and quick',
    nameAR: 'عملية تسجيل المستخدم واضحة وسريعة',
    pillar: 'Registration',
    pillarAR: 'التسجيل',
    subPillar: 'Ease of Use > Ease of Registration',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q23',
    dependsOnValue: 'yes',
    recommendation: 'Minimize registration steps; ask only essential fields',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 6: SERVICES & CONTENT INFORMATION (13 conditional questions)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q31',
    nameEN: 'Services list is available on:',
    nameAR: 'قائمة خدمات الجهة متوفرة من خلال:',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'List services on entity website or provide clear links to service directories',
  },
  {
    qid: 'Q32a',
    nameEN: 'Information is tailored to different user groups (e.g., Individuals, businesses)',
    nameAR: 'توفر معلومات مخصصة لفئات المستخدمين المختلفة (مثل الأفراد، الشركات)',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q31',
    dependsOnValue: 'entity_website',
    recommendation: 'Segment content by user groups (Individuals, Businesses) on services pages',
  },
  {
    qid: 'Q33a',
    nameEN: 'Website provided complete information in order to avail the required service (Fees, Service Procedures, Service Delivery Time, Required Documents)',
    nameAR: 'توفر معلومات كاملة من أجل الحصول على الخدمة المطلوبة (الرسوم، إجراءات الخدمة، المدة الزمنية، الوثائق المطلوبة، وقنوات تقديم الخدمة)',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q31',
    dependsOnValue: 'entity_website',
    recommendation: 'Include fees, steps, timeline, and required documents for each service',
  },
  {
    qid: 'Q34a',
    nameEN: "Information are consistent with information listed on entity's service catalogue",
    nameAR: 'توافق المعلومات المقدمة مع المعلومات المذكورة في دليل خدمات الجهة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'entity_website',
    recommendation: 'Keep website service information synchronized with official service catalogue',
  },
  {
    qid: 'Q32b',
    nameEN: 'Information is tailored to different user groups (e.g., Individuals, businesses)',
    nameAR: 'توفر معلومات مخصصة لفئات المستخدمين المختلفة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'directs_to_tamm',
    recommendation: 'Check Tamm website for user group segmentation in service information',
  },
  {
    qid: 'Q33b',
    nameEN: 'Website provided complete information in order to avail the required service',
    nameAR: 'توفر معلومات كاملة من أجل الحصول على الخدمة المطلوبة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'directs_to_tamm',
    recommendation: 'Verify Tamm website contains complete service delivery information',
  },
  {
    qid: 'Q34b',
    nameEN: "Information are consistent with information listed on entity's service catalogue",
    nameAR: 'توافق المعلومات المقدمة مع المعلومات المذكورة في دليل خدمات الجهة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'directs_to_tamm',
    recommendation: 'Confirm Tamm-listed information matches entity service catalogue',
  },
  {
    qid: 'Q32c',
    nameEN: 'Information is tailored to different user groups',
    nameAR: 'توفر معلومات مخصصة لفئات المستخدمين المختلفة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'navigating_tamm',
    recommendation: 'Check Tamm website navigation for user group information',
  },
  {
    qid: 'Q33c',
    nameEN: 'Website provided complete information in order to avail the required service',
    nameAR: 'توفر معلومات كاملة من أجل الحصول على الخدمة المطلوبة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'navigating_tamm',
    recommendation: 'Verify completeness of information via Tamm navigation',
  },
  {
    qid: 'Q34c',
    nameEN: "Information are consistent with information listed on entity's service catalogue",
    nameAR: 'توافق المعلومات المقدمة مع المعلومات المذكورة في دليل خدمات الجهة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'navigating_tamm',
    recommendation: 'Ensure Tamm information aligns with entity service catalogue',
  },
  {
    qid: 'Q32d',
    nameEN: 'Information is tailored to different user groups',
    nameAR: 'توفر معلومات مخصصة لفئات المستخدمين المختلفة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'navigating_atlp',
    recommendation: 'Check ATLP website for user group tailored information',
  },
  {
    qid: 'Q33d',
    nameEN: 'Website provided complete information in order to avail the required service',
    nameAR: 'توفر معلومات كاملة من أجل الحصول على الخدمة المطلوبة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'navigating_atlp',
    recommendation: 'Verify ATLP website provides complete service information',
  },
  {
    qid: 'Q34d',
    nameEN: "Information are consistent with information listed on entity's service catalogue",
    nameAR: 'توافق المعلومات المقدمة مع المعلومات المذكورة في دليل خدمات الجهة',
    pillar: 'Services',
    pillarAR: 'الخدمات ومعلومات المحتوى',
    subPillar: 'Information Quality',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q31',
    dependsOnValue: 'navigating_atlp',
    recommendation: 'Confirm ATLP information matches entity service catalogue',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 7: PERFORMANCE & STABILITY (4 questions, 6 max points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q26',
    nameEN: 'The website operates smoothly during normal use without crashes, bugs, glitches, broken links, or errors during the assessment.',
    nameAR: 'يعمل الموقع بسلاسة أثناء الاستخدام الاعتيادي دون حدوث أعطال أو أخطاء أو روابط معطلة أو مشكلات تقنية خلال التقييم.',
    pillar: 'Performance',
    pillarAR: 'الأداء والاستقرار',
    subPillar: 'Ease of Use > Stability',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Monitor console for errors; test all major user flows for JavaScript errors and failed requests',
  },
  {
    qid: 'Q27',
    nameEN: 'No bugs, glitches, broken links or errors are encountered during the assessment',
    nameAR: 'عدم مواجهة أي أخطاء أو عيوب أو روابط معطلة أو صفحات خطأ خلال التقييم',
    pillar: 'Performance',
    pillarAR: 'الأداء والاستقرار',
    subPillar: 'Ease of Use > Stability',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Crawl all links and verify no 404 or 500 errors are returned',
  },
  {
    qid: 'Q29',
    nameEN: 'No noticeable lag or delay during navigation',
    nameAR: 'عدم وجود تأخير أو بطئ ملحوظ أثناء التنقل بين الصفحات والروابط',
    pillar: 'Performance',
    pillarAR: 'الأداء والاستقرار',
    subPillar: 'Ease of Use > Performance',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Optimize page load and transition times; aim for < 3 seconds per page',
  },
  {
    qid: 'Q67',
    nameEN: 'All pages load within 3 seconds (homepage, other pages, and search results). Note: Make sure you have good internet connection.',
    nameAR: 'يتم تحميل جميع الصفحات في غضون 3 ثوانٍ (الصفحة الرئيسية، الصفحات الأخرى، ونتائج البحث).',
    pillar: 'Performance',
    pillarAR: 'الأداء والاستقرار',
    subPillar: 'Speed > Load Time',
    maxScore: 3,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Optimize asset delivery; minimize CSS/JS; enable caching; use CDN',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 8: CUSTOMER PRIVACY (3 questions, 3 max points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q35.1',
    nameEN: 'Privacy policy is available',
    nameAR: 'توفر صفحة سياسة الخصوصية',
    pillar: 'Customer Privacy',
    pillarAR: 'خصوصية العملاء',
    subPillar: 'Customer Privacy > Policy Transparency',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add Privacy Policy link in footer or header; ensure it stays on same domain',
  },
  {
    qid: 'Q35',
    nameEN: 'Privacy policy is easy to find and clearly explains data handling practices',
    nameAR: 'سهولة الوصول إلى صفحة سياسة الخصوصية ووضوحها',
    pillar: 'Customer Privacy',
    pillarAR: 'خصوصية العملاء',
    subPillar: 'Customer Privacy > Policy Transparency',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q35.1',
    dependsOnValue: 'yes',
    recommendation: 'Ensure Privacy Policy is accessible from main footer and explains data practices',
  },
  {
    qid: 'Q36',
    nameEN: 'Secure registration / login and transaction processes are in place',
    nameAR: 'عمليات تسجيل المستخدمين وتسجيل الدخول آمنة',
    pillar: 'Customer Privacy',
    pillarAR: 'خصوصية العملاء',
    subPillar: 'Customer Privacy > Data Security',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q23',
    dependsOnValue: 'yes',
    recommendation: 'Use HTTPS/SSL; password fields should be masked; implement secure authentication',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 9: LIVE CHAT JOURNEY (20+ manual questions, ~20 scored points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q37',
    nameEN: 'Live chat feature is available on the website',
    nameAR: 'توفر خاصية الدردشة الحية من خلال الموقع الإلكتروني',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Accessibility > Availability',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    recommendation: 'Implement live chat widget (Intercom, Zendesk, Tidio, or custom)',
  },
  {
    qid: 'Q38',
    nameEN: 'Live chat is powered by Tamm',
    nameAR: 'تتوفر خاصية الدردشة الحية المدعومة من "تم"',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Accessibility > Availability',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q37',
    dependsOnValue: 'yes',
    recommendation: 'Integrate Tamm-powered live chat for consistent support',
  },
  {
    qid: 'Q39',
    nameEN: 'Live chat feature loaded within:',
    nameAR: 'تم تحميل خاصية الدردشة الحية خلال:',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Speed > Load Time',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q38',
    dependsOnValue: 'not_tamm',
    recommendation: 'Optimize chat widget load time to < 2 seconds',
  },
  {
    qid: 'Q40',
    nameEN: 'Live chat working hours are clearly listed',
    nameAR: 'توفر ساعات عمل الدردشة الحية ووضوحها',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Ease of Use > Clarity',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q38',
    dependsOnValue: 'not_tamm',
    recommendation: 'Display working hours clearly near chat widget',
  },
  {
    qid: 'Q41',
    nameEN: 'Live chat support is available during stated hours',
    nameAR: 'توفر الدعم من خلال الدردشة الحية خلال الساعات المذكورة',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Ease of Use > Availability',
    maxScore: 3,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q40',
    dependsOnValue: 'yes',
    recommendation: 'Ensure agents are available during posted hours',
  },
  {
    qid: 'Q42',
    nameEN: 'Query was submitted successfully through live chat',
    nameAR: 'التمكن من تقديم الاستفسار بنجاح من خلال الدردشة الحية',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Accessibility > Functionality',
    maxScore: 3,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q38',
    dependsOnValue: 'not_tamm',
    recommendation: 'Ensure test message can be sent and received in chat',
  },
  {
    qid: 'Q43',
    nameEN: 'Type of available support (virtual, human)',
    nameAR: 'اختر نوع الدعم الذي تلقيته (افتراضي، موظف بشري)',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Ease of Use > Support',
    maxScore: 3,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q42',
    dependsOnValue: 'yes',
    recommendation: 'Provide both AI assistant and human agent support when possible',
  },
  {
    qid: 'Q44b',
    nameEN: 'Time to reply to the query by the human agent is within reasonable time',
    nameAR: 'الوقت الذي استغرقه الموظف للرد على الاستفسار مناسب (موظف بشري)',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Speed > Response Time',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human',
    recommendation: 'Aim for human agent response within 1 minute',
  },
  {
    qid: 'Q45',
    nameEN: 'Human agent welcomed using a standard greeting (e.g., Hello, Salam Alaikom, Welcome to [entity name])',
    nameAR: 'يستخدم الموظف الافتراضي تحية معيارية مثلا مرحبا والسلام عليكم.. (مرحبا الى (اسم الجهة)',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 3,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Train agents to greet users with professional, warm greeting',
  },
  {
    qid: 'Q46',
    nameEN: 'Human agent uses a professional and respectful tone',
    nameAR: 'الموظف استخدم نبرة مهنية ومحترمة في الرد.',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Professionalism',
    maxScore: 3,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Train agents on professional communication standards',
  },
  {
    qid: 'Q46b',
    nameEN: 'Human agent addressed customer by their name or using a friendly/professional expression like "dear customer"',
    nameAR: 'الموظف (بشري/افتراضي) خاطب المتعامل باسمه أو استخدم تعبيرًا ودودًا / مهنيًا مثل "عزيزي المتعامل".',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Encourage personalized addressing in agent responses',
  },
  {
    qid: 'Q47',
    nameEN: 'Human agent was able to communicate in the preferred language',
    nameAR: 'تمكن الموظف الافتراضي على التواصل باللغة المفضلة',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Provide bilingual (Arabic/English) support agents',
  },
  {
    qid: 'Q47b',
    nameEN: "Human agent used simple language, clear and concise to ensure customer's understanding",
    nameAR: 'استخدم الموظف (بشري/افتراضي) لغة ودية وواضحة وبسيطة لضمان فهم المتعامل',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Train agents to use plain, simple language avoiding jargon',
  },
  {
    qid: 'Q47c',
    nameEN: 'Human agent statements were formal and free from contractions (e.g., "don\'t", "shouldn\'t"), technical terms, abbreviations, acronyms, or sensitive information.',
    nameAR: 'استخدم الموظف (بشري/افتراضي) لغة رسمية وخالية من الاختصارات، ومن المصطلحات الفنية، أو الرموز المختصرة، أو المعلومات الحساسة.',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Establish formal communication standards avoiding contractions and acronyms',
  },
  {
    qid: 'Q49b',
    nameEN: 'Human agent wrote dates and numbers in the following manner: Dates: 15 April 2025 (Date Month Year), Clock system: 10:30AM, Money: AED 35,000, Telephone: +971 50 123 4567',
    nameAR: 'كتب الموظف التواريخ والأرقام بالطريقة الصحيحة',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Establish formatting standards for dates, numbers, and currency',
  },
  {
    qid: 'Q52b',
    nameEN: 'Human agent response was free of spelling and grammatical mistakes.',
    nameAR: 'استجابة الموظف (البشري/الافتراضي) خالية من الأخطاء الإملائية والنحوية.',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Professionalism',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Implement spell-check and review before sending agent responses',
  },
  {
    qid: 'Q50',
    nameEN: 'Human agent asked or offered further assistance',
    nameAR: 'قام الموظف (بشري/افتراضي) بالسؤال عن الحاجة إلى المزيد من المساعدة أو عرض المزيد من المساعدة',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 2,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Train agents to proactively ask if additional help is needed',
  },
  {
    qid: 'Q51',
    nameEN: 'Human agent thanked the customer for reaching out for support anywhere in the conversation',
    nameAR: 'الموظف (بشري/افتراضي) شكر المتعامل على تواصله وطلبه للدعم، في أي جزء من المحادثة',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 2,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Include gratitude message in agent closing remarks',
  },
  {
    qid: 'Q51a',
    nameEN: 'Did the human agent summarise the key points discussed and confirm that the customer\'s needs have been fully addressed?',
    nameAR: 'هل قام الموظف بتلخيص النقاط الرئيسية التي تمت مناقشتها والتأكد من تلبية جميع احتياجاتك؟',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Train agents to summarize and confirm before ending chat',
  },
  {
    qid: 'Q51b',
    nameEN: 'Did the human agent provide clear instructions for any necessary follow-up actions and clarify next steps if needed?',
    nameAR: 'هل قدّم الموظف تعليمات واضحة بخصوص أي إجراءات متابعة ضرورية ووضّح الخطوات التالية إذا لزم الأمر؟',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Soft Skills',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Provide clear next steps and follow-up instructions to customer',
  },
  {
    qid: 'Q49',
    nameEN: 'Human agent was helpful in providing an answer to the query (e.g., process, fees, timeline, etc.)',
    nameAR: 'كان الموظف (البشري/الافتراضي) مفيدًا في تقديم إجابة على الاستفسار (مثل الإجراءات، الرسوم، المدة الزمنية، وغيرها).',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Staff Knowledge',
    maxScore: 2,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Equip agents with comprehensive knowledge base and service information',
  },
  {
    qid: 'Q52',
    nameEN: "Information provided by the human agent are consistent with information listed on entity's catalogue",
    nameAR: 'توافق المعلومات المقدمة من الموظف مع المعلومات المذكورة في دليل خدمات الجهة',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Information Quality > Accuracy',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q49',
    dependsOnValue: 'yes_or_directed',
    recommendation: 'Regularly train agents on accurate service information',
  },
  {
    qid: 'Q52c',
    nameEN: 'Human agent offered a satisfaction survey at the end of the conversation',
    nameAR: 'يقدّم الموظف (البشري أو الافتراضي) استطلاع رضا في نهاية المحادثة',
    pillar: 'Live Chat',
    pillarAR: 'رحلة الدردشة الحية',
    subPillar: 'Live Chat - Staff Professionalism > Professionalism',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q43',
    dependsOnValue: 'human_or_both',
    recommendation: 'Enable post-chat satisfaction survey widget',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 10: ENQUIRY FORM JOURNEY (18+ manual questions, ~18 scored points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q53',
    nameEN: 'Enquiry form available on the website',
    nameAR: 'تتوفر خاصية نموذج الاستفسار على الموقع الإلكتروني',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Accessibility > Availability',
    maxScore: 0,
    isScored: false,
    isAutomatic: true,
    checkType: 'auto',
    recommendation: 'Add contact form with required fields (name, email, message)',
  },
  {
    qid: 'Q54',
    nameEN: 'Successfully able to submit enquiry through enquiry form',
    nameAR: 'التمكن من تقديم الاستفسار بنجاح من خلال نموذج الاستفسار',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Ease of Use > Functionality',
    maxScore: 2,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q53',
    dependsOnValue: 'yes',
    recommendation: 'Ensure form submission works without errors',
  },
  {
    qid: 'Q55',
    nameEN: '"Thank you" message displayed post submission',
    nameAR: 'يتم عرض رسالة شكر للمتعامل بعد الضغط على زر الإرسال',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Ease of Use > Confirmation',
    maxScore: 1,
    isScored: true,
    isAutomatic: true,
    checkType: 'auto',
    dependsOn: 'Q54',
    dependsOnValue: 'yes',
    recommendation: 'Show confirmation message or redirect to thank you page',
  },
  {
    qid: 'Q56',
    nameEN: 'Automatic reply is received upon submission or a message stating that the submission is successful',
    nameAR: 'استلام رد تلقائي عند الإرسال أو رسالة تؤكد نجاح الإرسال',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Speed > Confirmation Time',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q54',
    dependsOnValue: 'yes',
    recommendation: 'Set up automated email response upon form submission',
  },
  {
    qid: 'Q57',
    nameEN: 'Auto-Reply is received from:',
    nameAR: 'تم استلام الرد التلقائي من:',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Ease of Use',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q56',
    dependsOnValue: 'yes',
    recommendation: 'Send auto-reply from entity email address',
  },
  {
    qid: 'Q58',
    nameEN: 'Automated response was free from spelling and grammatical errors',
    nameAR: 'يخلو الرد الآلي من الأخطاء الإملائية والنحوية',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Accuracy',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q56',
    dependsOnValue: 'yes',
    recommendation: 'Proofread automated response template before deployment',
  },
  {
    qid: 'Q58b',
    nameEN: 'Automated response or message specifies the time needed for the entity to revert back and next steps',
    nameAR: 'الرد التلقائي أو الرسالة توضح المدة المتوقعة لرد الجهة والخطوات التالية',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Accuracy',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q56',
    dependsOnValue: 'yes',
    recommendation: 'Include expected response timeframe and next steps in auto-reply',
  },
  {
    qid: 'Q59',
    nameEN: 'Personalized reply is received within reasonable time. Mention exact time (e.g., 1 day and 2 hours).',
    nameAR: 'تم استلام الرد من الموظف خلال مدة زمنية مناسبة. اذكر الوقت بشكل دقيق.',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Speed > Response Time',
    maxScore: 2,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q54',
    dependsOnValue: 'yes',
    recommendation: 'Aim to respond to enquiries within 1 business day',
  },
  {
    qid: 'Q59b',
    nameEN: 'Reply received through:',
    nameAR: 'تم استلام الرد من خلال:',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Ease of Use',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59',
    dependsOnValue: 'yes',
    recommendation: 'Respond via email by default; SMS/call as secondary channel',
  },
  {
    qid: 'Q60',
    nameEN: 'Reply is received from:',
    nameAR: 'تم استلام الرد من الموظف من:',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Ensure reply is from entity staff, not automated generic response',
  },
  {
    qid: 'Q61',
    nameEN: 'Received proper salutation (Good Morning/Afternoon…)',
    nameAR: 'استخدم الموظف تحية مناسبة (صباح الخير/مساء الخير...)',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Train staff to include professional greeting in email responses',
  },
  {
    qid: 'Q62',
    nameEN: 'Response was free from any spelling or grammatical error',
    nameAR: 'يخلو الرد من الموظف من أي أخطاء إملائية أو نحوية',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Professionalism',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Implement spell-check and review process before sending',
  },
  {
    qid: 'Q63',
    nameEN: 'Agent communicated in the preferred language',
    nameAR: 'استخدم الموظف اللغة المفضلة للرد على الاستفسار من خلال البريد الإلكتروني',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Support bilingual (Arabic/English) email responses',
  },
  {
    qid: 'Q63b',
    nameEN: 'Agent communicates in a professional tone, using clear and simple language, with statements formal and free from contractions, technical terms, abbreviations, acronyms, etc.',
    nameAR: 'يتواصل الموظف بنبرة مهنية مستخدماً لغة واضحة وبسيطة، مع عبارات رسمية وخالية من الاختصارات',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Agent Reply',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Provide communication guidelines to staff',
  },
  {
    qid: 'Q63c',
    nameEN: "Agent used simple language, clear and concise to ensure customer's understanding",
    nameAR: 'استخدم الموظف لغة ودية وواضحة وبسيطة لضمان فهم المتعامل',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Train staff to use plain, accessible language',
  },
  {
    qid: 'Q63d',
    nameEN: 'Agent statements were formal and free from contractions such as "don\'t", "shouldn\'t", or technical terms, abbreviations, acronyms, or sensitive information.',
    nameAR: 'استخدم الموظف لغة رسمية وخالية من الاختصارات، ومن المصطلحات الفنية، أو الرموز المختصرة، أو المعلومات الحساسة.',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Agent Reply',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Establish formal communication standards',
  },
  {
    qid: 'Q63e',
    nameEN: 'Agent wrote dates and numbers in the following manner: Dates: 15 April 2025 (Date Month Year), Clock: 10:30AM, Money: AED 35,000, Telephone: +971 50 123 4567',
    nameAR: 'كتب الموظف التواريخ والأرقام بالطريقة الصحيحة',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Agent Reply',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Establish formatting standards for dates, numbers, currency',
  },
  {
    qid: 'Q63f',
    nameEN: 'Agent thanked the customer for reaching out for support anywhere in the email',
    nameAR: 'الموظف شكر المتعامل على تواصله وطلبه للدعم، في أي جزء من البريد الإلكتروني.',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Agent Reply',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Include gratitude in email closing',
  },
  {
    qid: 'Q64',
    nameEN: 'Agent provided required details on the query (e.g., process, fees, timeline, etc.)',
    nameAR: 'تمكن الموظف من تقديم التفاصيل المطلوبة حول الاستفسار مثلا: عملية الحصول على الخدمة، الرسوم، الوقت، الخ.',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Information Quality > Staff Knowledge',
    maxScore: 2,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Ensure staff have access to complete service information',
  },
  {
    qid: 'Q65',
    nameEN: 'Agent followed proper email closure protocol/standards (e.g., Best Regards, Name of agent, or positive closing statement)',
    nameAR: 'استخدم الموظف بروتوكول/معايير إنهاء البريد الإلكتروني المناسبة (مثلا: مع أطيب الامنيات، اسم الموظف أو عبارة ايجابية في آخر الرد)',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Staff Professionalism > Soft Skills',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q59b',
    dependsOnValue: 'email_or_sms',
    recommendation: 'Include formal closing signature in all emails',
  },
  {
    qid: 'Q66',
    nameEN: "Information provided by the agent are consistent with information listed on entity's catalogue",
    nameAR: 'توافق المعلومات المقدمة من الموظف مع المعلومات المذكورة في دليل خدمات الجهة',
    pillar: 'Enquiry Form Journey',
    pillarAR: 'رحلة نموذج الاستفسار',
    subPillar: 'Enquiry Form - Information Quality > Accuracy',
    maxScore: 1,
    isScored: true,
    isAutomatic: false,
    checkType: 'manual',
    dependsOn: 'Q64',
    dependsOnValue: 'yes',
    recommendation: 'Keep staff informed of any service changes or updates',
  },

  // ═══════════════════════════════════════════════════════════════════
  // PILLAR 11: MS KEY OBSERVATIONS (1 open-ended question, 0 points)
  // ═══════════════════════════════════════════════════════════════════

  {
    qid: 'Q68',
    nameEN: 'Please detail the key observations across the journey',
    nameAR: 'يرجى تسجيل الملاحظات الرئيسية بدقة وتفصيل',
    pillar: 'MS Key Observations',
    pillarAR: 'الملاحظات الرئيسية للتقييم',
    subPillar: 'Final Observations',
    maxScore: 0,
    isScored: false,
    isAutomatic: false,
    checkType: 'openended',
    recommendation: 'Document key findings and recommendations from the assessment',
  },
];

// ════════════════════════════════════════════════════════════════════
// SCORING FUNCTIONS
// ════════════════════════════════════════════════════════════════════

export function getCriterion(qid: string): CriterionDefinition | undefined {
  return CRITERIA.find((c) => c.qid === qid);
}

export function getRecommendation(qid: string): string {
  const criterion = getCriterion(qid);
  return criterion?.recommendation ?? '';
}

export function calculateTotalScore(results: CriterionResult[]): {
  total: number;
  max: number;
  percentage: number;
  grade: string;
} {
  let earned = 0;
  let max = 0;

  for (const result of results) {
    // 'pending' = awaiting an async email reply (Pillar 10); excluded from the
    // score like na/skipped until the background poller resolves it.
    if (result.status !== 'na' && result.status !== 'skipped' && result.status !== 'pending') {
      const criterion = getCriterion(result.qid);
      if (criterion && criterion.isScored) {
        earned += result.scoreEarned;
        max += result.maxScore;
      }
    }
  }

  const percentage = max > 0 ? Math.round((earned / max) * 100) : 0;
  let grade: Grade = 'Needs Improvement';
  if (percentage >= 90) grade = 'Excellent';
  else if (percentage >= 75) grade = 'Good';
  else if (percentage >= 60) grade = 'Satisfactory';

  return { total: earned, max, percentage, grade };
}

export function calculatePillarScores(results: CriterionResult[]): PillarScore[] {
  const pillarMap = new Map<string, { pillarAR: string; earned: number; max: number }>();

  for (const r of results) {
    if (r.status === 'na' || r.status === 'skipped' || r.status === 'pending') continue;

    const criterion = getCriterion(r.qid);
    if (!criterion || !criterion.isScored) continue;

    if (!pillarMap.has(r.pillar)) {
      pillarMap.set(r.pillar, {
        pillarAR: criterion.pillarAR,
        earned: 0,
        max: 0,
      });
    }
    const entry = pillarMap.get(r.pillar)!;
    entry.earned += r.scoreEarned;
    entry.max += r.maxScore;
  }

  const scores: PillarScore[] = [];
  const pillarOrder = [
    'Discovery & Access',
    'Accessibility & Inclusion',
    'Website Structure',
    'Navigation',
    'Registration',
    'Services',
    'Performance',
    'Customer Privacy',
    'Live Chat',
    'Enquiry Form Journey',
    'MS Key Observations',
  ];

  for (const pillar of pillarOrder) {
    const data = pillarMap.get(pillar);
    if (data) {
      scores.push({
        pillar,
        pillarAR: data.pillarAR,
        earned: data.earned,
        max: data.max,
        percentage: data.max > 0 ? Math.round((data.earned / data.max) * 100) : 0,
      });
    }
  }

  return scores;
}
